spring:

  datasource:
    url: jdbc:mysql://localhost:3306/db_spring_rest
    username: root
    password: root
    driver:
      class: 
        name: com.mysql.jdbc.Driver

  hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        